"""user table

Revision ID: 6db7ec000754
Revises: fd02d3ded3b5
Create Date: 2021-10-25 23:35:40.074796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db7ec000754'
down_revision = 'fd02d3ded3b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('file', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'file', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
